---
title: "Installation Instructions for scRepertoire"
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output: rmarkdown::html_vignette
theme: united
df_print: kable
vignette: >
  %\VignetteIndexEntry{Installation Instructions for scRepertoire}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<style>
p.caption {
  font-size: 0.9em;
}
</style>
 
```{r setup, include=FALSE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  time_it = TRUE
)
```

## GitHub Branches
`scRepertoire` is an active project with frequent updates based on user feedback. The most up-to-date versions are available via its GitHub repositories. These versions can be installed using `devtools::install_github()` or `remotes::install_github()`

[immApex](https://github.com/BorchLab/immApex) is now a  required is now a required dependency for the underlying processes of `scRepertoire`. Ensure both are called during installation if not using Bioconductor.

### Demonstrating GitHub Installation

To install `scRepertoire` and its `immApex` dependency directly from GitHub:

```
remotes::install_github(c("BorchLab/immApex", "BorchLab/scRepertoire"))
```

## Bioconductor

The current stable version of `scRepertoire` is also available through Bioconductor.

```
BiocManager::install("scRepertoire")
```

## Release Notes  
A full copy of the changes in each version can be found in the [NEWS/ChangeLog](https://borch.dev/uploads/scRepertoire/news/index.html).
