# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppGetAaKmerPercent <- function(seqs, motifs, k) {
    .Call(`_scRepertoire_rcppGetAaKmerPercent`, seqs, motifs, k)
}

rcppGenerateUniqueNtMotifs <- function(k) {
    .Call(`_scRepertoire_rcppGenerateUniqueNtMotifs`, k)
}

rcppGetNtKmerPercent <- function(seqs, k) {
    .Call(`_scRepertoire_rcppGetNtKmerPercent`, seqs, k)
}

constructBarcodeIndex <- function(conDfBarcodes, data2Barcodes) {
    .Call(`_scRepertoire_constructBarcodeIndex`, conDfBarcodes, data2Barcodes)
}

