# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' @keywords internal
rcpp_hello_world <- function() {
    invisible(.Call(`_scRepertoire_rcpp_hello_world`))
}

